using System.Reflection;
using System.Text;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;
using DotnetEfCoreMcp.Server.DbContextDiscovery;
using DotnetEfCoreMcp.Server.Querying;

namespace DotnetEfCoreMcp.Server.Compilation;

/// <summary>Builds the ephemeral C# compilation unit containing a query-specific DbContext subclass.</summary>
internal static class UserQuerySourceGenerator
{
    private const string GeneratedNamespace = "DotnetEfCoreMcp.Server.CompiledQueries";

    internal static GeneratedUserQuerySource Generate(Type contextType, string query, string token)
    {
        ArgumentNullException.ThrowIfNull(contextType);
        ArgumentException.ThrowIfNullOrWhiteSpace(query);
        ArgumentException.ThrowIfNullOrWhiteSpace(token);

        var constructorShape = DbContextActivator.DetermineConstructorShape(contextType);
        if (constructorShape is DbContextConstructorShape.Unsupported)
        {
            throw new QueryExecutionException(
                "The selected DbContext cannot be used with the Roslyn query engine because it does not expose a public parameterless or DbContextOptions constructor, and does not implement IDesignTimeDbContextFactory<TContext>.");
        }

        if (constructorShape is DbContextConstructorShape.DesignTimeFactory)
        {
            return GenerateFactoryStaticMethod(contextType, query, token);
        }

        var className = $"UserQuery_{token}";
        var contextTypeName = GetGlobalTypeName(contextType);
        var statementMode = IsStatementMode(query);
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("using System.Linq;");
        builder.AppendLine("using Microsoft.EntityFrameworkCore;");
        foreach (var ns in CollectQueryNamespaces(contextType))
        {
            builder.Append("using ").Append(ns).AppendLine(";");
        }

        builder.Append("namespace ").Append(GeneratedNamespace).AppendLine(";");
        builder.AppendLine();
        builder.Append("public sealed class ").Append(className).Append(" : ").Append(contextTypeName).AppendLine();
        builder.AppendLine("{");
        AppendConstructor(builder, className, contextTypeName, constructorShape);
        builder.AppendLine();
        builder.AppendLine("    protected override void OnConfiguring(global::Microsoft.EntityFrameworkCore.DbContextOptionsBuilder optionsBuilder)");
        builder.AppendLine("    {");
        builder.AppendLine("        base.OnConfiguring(optionsBuilder);");
        builder.AppendLine("        optionsBuilder.UseQueryTrackingBehavior(global::Microsoft.EntityFrameworkCore.QueryTrackingBehavior.NoTracking);");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public override int SaveChanges()");
        builder.AppendLine("    {");
        builder.AppendLine("        EnsureMutationsAllowed();");
        builder.AppendLine("        return base.SaveChanges();");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public override int SaveChanges(bool acceptAllChangesOnSuccess)");
        builder.AppendLine("    {");
        builder.AppendLine("        EnsureMutationsAllowed();");
        builder.AppendLine("        return base.SaveChanges(acceptAllChangesOnSuccess);");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public override global::System.Threading.Tasks.Task<int> SaveChangesAsync(global::System.Threading.CancellationToken cancellationToken = default)");
        builder.AppendLine("    {");
        builder.AppendLine("        EnsureMutationsAllowed();");
        builder.AppendLine("        return base.SaveChangesAsync(cancellationToken);");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public override global::System.Threading.Tasks.Task<int> SaveChangesAsync(bool acceptAllChangesOnSuccess, global::System.Threading.CancellationToken cancellationToken = default)");
        builder.AppendLine("    {");
        builder.AppendLine("        EnsureMutationsAllowed();");
        builder.AppendLine("        return base.SaveChangesAsync(acceptAllChangesOnSuccess, cancellationToken);");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    private void EnsureMutationsAllowed()");
        builder.AppendLine("    {");
        builder.AppendLine("        if (!_allowMutations)");
        builder.AppendLine("        {");
        builder.AppendLine("            throw new global::DotnetEfCoreMcp.Server.Querying.QueryExecutionException(\"Saving changes from run_query is disabled for this connection.\");");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public object? RunUserAuthoredQuery()");
        builder.AppendLine("    {");

        var queryStartLine = CountLines(builder) + 1;
        if (statementMode)
        {
            AppendIndentedVerbatim(builder, query, 2);
            if (!query.EndsWith('\n'))
            {
                builder.AppendLine();
            }
        }
        else
        {
            builder.Append("        return ").Append(query).AppendLine(";");
        }

        builder.AppendLine("    }");
        builder.AppendLine("}");

        return new GeneratedUserQuerySource(
            builder.ToString(),
            $"{GeneratedNamespace}.{className}",
            queryStartLine - 1,
            statementMode);
    }

    /// <summary>Generates a query for a <see cref="DbContextConstructorShape.DesignTimeFactory"/>
    /// context. Unlike the subclass-based shapes above, the server never constructs an instance of
    /// this context itself (the caller must trust the target's own
    /// <c>IDesignTimeDbContextFactory&lt;TContext&gt;</c> to resolve its connection - see
    /// docs/development/startup-derived-connections.md), so there is no constructor to add a
    /// <c>bool allowMutations</c> parameter to and no subclass to override <c>SaveChanges</c>/
    /// <c>OnConfiguring</c> on. Instead this emits a single <c>public static object? RunUserAuthoredQuery
    /// ({contextTypeName} context)</c> method taking the already-constructed context as a parameter;
    /// the caller (<see cref="Querying.RoslynQueryExecutor"/>) is responsible for applying
    /// <c>QueryTrackingBehavior.NoTracking</c> and blocking mutations (via <c>SavingChanges</c>) on the
    /// real context instance before invoking this method.</summary>
    private static GeneratedUserQuerySource GenerateFactoryStaticMethod(Type contextType, string query, string token)
    {
        var className = $"UserQuery_{token}";
        var contextTypeName = GetGlobalTypeName(contextType);
        var statementMode = IsStatementMode(query);
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("using System.Linq;");
        builder.AppendLine("using Microsoft.EntityFrameworkCore;");
        foreach (var ns in CollectQueryNamespaces(contextType))
        {
            builder.Append("using ").Append(ns).AppendLine(";");
        }

        builder.Append("namespace ").Append(GeneratedNamespace).AppendLine(";");
        builder.AppendLine();
        builder.Append("public static class ").Append(className).AppendLine();
        builder.AppendLine("{");
        builder.Append("    public static object? RunUserAuthoredQuery(").Append(contextTypeName).AppendLine(" context)");
        builder.AppendLine("    {");

        // Subclass-based generation (above) lets the query text reference DbSet<T> properties
        // unqualified (e.g. "Users.Where(...)") because the generated class inherits the context and
        // those properties resolve via `this`. There is no `this` in this static method, so each public
        // DbSet<T> property is aliased to a same-named local pointing at `context.{Property}` to keep
        // the exact same unqualified-access authoring experience.
        foreach (var propertyName in GetDbSetPropertyNames(contextType))
        {
            builder.Append("        var ").Append(propertyName).Append(" = context.").Append(propertyName).AppendLine(";");
        }

        var queryStartLine = CountLines(builder) + 1;
        if (statementMode)
        {
            AppendIndentedVerbatim(builder, query, 2);
            if (!query.EndsWith('\n'))
            {
                builder.AppendLine();
            }
        }
        else
        {
            builder.Append("        return ").Append(query).AppendLine(";");
        }

        builder.AppendLine("    }");
        builder.AppendLine("}");

        return new GeneratedUserQuerySource(
            builder.ToString(),
            $"{GeneratedNamespace}.{className}",
            queryStartLine - 1,
            statementMode);
    }

    private static void AppendConstructor(
        StringBuilder builder,
        string className,
        string contextTypeName,
        DbContextConstructorShape constructorShape)
    {
        builder.AppendLine("    private readonly bool _allowMutations;");
        builder.AppendLine();

        switch (constructorShape)
        {
            case DbContextConstructorShape.GenericOptions:
                builder.Append("    public ").Append(className)
                    .Append("(global::Microsoft.EntityFrameworkCore.DbContextOptions<")
                    .Append(contextTypeName).AppendLine("> options, bool allowMutations)");
                builder.AppendLine("        : base(options)");
                break;

            case DbContextConstructorShape.NonGenericOptions:
                builder.Append("    public ").Append(className)
                    .AppendLine("(global::Microsoft.EntityFrameworkCore.DbContextOptions options, bool allowMutations)");
                builder.AppendLine("        : base(options)");
                break;

            case DbContextConstructorShape.Parameterless:
                builder.Append("    public ").Append(className).AppendLine("(bool allowMutations)");
                builder.AppendLine("        : base()");
                break;

            default:
                throw new InvalidOperationException($"Unsupported DbContext constructor shape '{constructorShape}'.");
        }

        builder.AppendLine("    {");
        builder.AppendLine("        _allowMutations = allowMutations;");
        builder.AppendLine("    }");
    }

    private static bool IsStatementMode(string query)
    {
        var expression = SyntaxFactory.ParseExpression(query);
        if (!expression.ContainsDiagnostics && expression.FullSpan.End == query.Length)
        {
            return false;
        }

        var statements = SyntaxFactory.ParseStatement($"{{{query}}}") as BlockSyntax;
        return statements is not null && !statements.ContainsDiagnostics;
    }

    /// <summary>Returns the names of every public <c>DbSet&lt;T&gt;</c> property on
    /// <paramref name="contextType"/>, used by <see cref="GenerateFactoryStaticMethod"/> to alias each
    /// one to a local variable so factory-backed queries can reference them unqualified just like the
    /// subclass-based generation path.</summary>
    private static IEnumerable<string> GetDbSetPropertyNames(Type contextType)
    {
        foreach (var property in contextType.GetProperties(BindingFlags.Public | BindingFlags.Instance))
        {
            if (property.PropertyType.IsGenericType
                && property.PropertyType.GetGenericTypeDefinition() == typeof(DbSet<>)
                && property.GetIndexParameters().Length == 0)
            {
                yield return property.Name;
            }
        }
    }

    /// <summary>Gathers the namespaces most likely to be referenced unqualified in a user-authored
    /// query: the DbContext's own namespace (covers <c>DbSet&lt;T&gt;</c> entity types typically
    /// declared alongside it, as well as enums like <c>PartnerType</c> that live next to the
    /// entity that uses them), plus the namespaces of every <c>DbSet&lt;T&gt;</c> entity type and
    /// the enum-typed properties declared directly on those entities. This lets simple query
    /// snippets refer to sibling types (e.g. <c>PartnerType.Transport</c>) without requiring full
    /// namespace qualification, mirroring how the inherited <c>DbSet</c> properties already
    /// resolve unqualified via member lookup on the generated subclass.</summary>
    private static IReadOnlyCollection<string> CollectQueryNamespaces(Type contextType)
    {
        var namespaces = new SortedSet<string>(StringComparer.Ordinal);

        AddNamespace(namespaces, contextType);

        foreach (var property in contextType.GetProperties(BindingFlags.Public | BindingFlags.Instance))
        {
            if (!property.PropertyType.IsGenericType
                || property.PropertyType.GetGenericTypeDefinition() != typeof(DbSet<>))
            {
                continue;
            }

            var entityType = property.PropertyType.GetGenericArguments()[0];
            AddNamespace(namespaces, entityType);

            foreach (var entityProperty in entityType.GetProperties(BindingFlags.Public | BindingFlags.Instance))
            {
                var propertyType = entityProperty.PropertyType;
                var underlyingType = Nullable.GetUnderlyingType(propertyType) ?? propertyType;
                if (underlyingType.IsEnum)
                {
                    AddNamespace(namespaces, underlyingType);
                }
            }
        }

        return namespaces;
    }

    private static void AddNamespace(SortedSet<string> namespaces, Type type)
    {
        if (!string.IsNullOrEmpty(type.Namespace))
        {
            namespaces.Add(type.Namespace);
        }
    }

    private static void AppendIndentedVerbatim(StringBuilder builder, string text, int indentationLevel)
    {
        var indentation = new string(' ', indentationLevel * 4);
        builder.Append(indentation);
        builder.Append(text.Replace("\n", "\n" + indentation, StringComparison.Ordinal));
    }

    private static int CountLines(StringBuilder builder)
    {
        var lines = 0;
        foreach (var character in builder.ToString())
        {
            if (character == '\n')
            {
                lines++;
            }
        }

        return lines;
    }

    private static string GetGlobalTypeName(Type type)
    {
        if (type.IsGenericParameter)
        {
            return type.Name;
        }

        if (type.IsArray)
        {
            return $"{GetGlobalTypeName(type.GetElementType()!)}[]";
        }

        if (type.IsNested)
        {
            return $"{GetGlobalTypeName(type.DeclaringType!)}.{GetTypeName(type)}";
        }

        return $"global::{type.Namespace}.{GetTypeName(type)}";
    }

    private static string GetTypeName(Type type)
    {
        if (!type.IsGenericType)
        {
            return type.Name;
        }

        var tickIndex = type.Name.IndexOf('`');
        var name = tickIndex < 0 ? type.Name : type.Name[..tickIndex];
        var genericArguments = type.GetGenericArguments();
        return $"{name}<{string.Join(", ", genericArguments.Select(GetGlobalTypeName))}>";
    }
}

internal sealed record GeneratedUserQuerySource(
    string Source,
    string TypeName,
    int QueryHeaderLineCount,
    bool IsStatementMode);
