using System.Text;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using DotnetEfCoreMcp.Server.DbContextDiscovery;
using DotnetEfCoreMcp.Server.Querying;

namespace DotnetEfCoreMcp.Server.Compilation;

/// <summary>Builds the ephemeral C# compilation unit containing a query-specific DbContext subclass.</summary>
internal static class UserQuerySourceGenerator
{
    private const string GeneratedNamespace = "DotnetEfCoreMcp.Server.CompiledQueries";

    internal static GeneratedUserQuerySource Generate(Type contextType, string query, string token)
    {
        ArgumentNullException.ThrowIfNull(contextType);
        ArgumentException.ThrowIfNullOrWhiteSpace(query);
        ArgumentException.ThrowIfNullOrWhiteSpace(token);

        var constructorShape = DbContextActivator.DetermineConstructorShape(contextType);
        if (constructorShape is DbContextConstructorShape.DesignTimeFactory or DbContextConstructorShape.Unsupported)
        {
            throw new QueryExecutionException(
                "The selected DbContext cannot be used with the Roslyn query engine because it does not expose a public parameterless or DbContextOptions constructor.");
        }

        var className = $"UserQuery_{token}";
        var contextTypeName = GetGlobalTypeName(contextType);
        var statementMode = IsStatementMode(query);
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("using System.Linq;");
        builder.AppendLine("using Microsoft.EntityFrameworkCore;");
        builder.Append("namespace ").Append(GeneratedNamespace).AppendLine(";");
        builder.AppendLine();
        builder.Append("public sealed class ").Append(className).Append(" : ").Append(contextTypeName).AppendLine();
        builder.AppendLine("{");
        AppendConstructor(builder, className, contextTypeName, constructorShape);
        builder.AppendLine();
        builder.AppendLine("    protected override void OnConfiguring(global::Microsoft.EntityFrameworkCore.DbContextOptionsBuilder optionsBuilder)");
        builder.AppendLine("    {");
        builder.AppendLine("        base.OnConfiguring(optionsBuilder);");
        builder.AppendLine("        optionsBuilder.UseQueryTrackingBehavior(global::Microsoft.EntityFrameworkCore.QueryTrackingBehavior.NoTracking);");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public override int SaveChanges()");
        builder.AppendLine("    {");
        builder.AppendLine("        EnsureMutationsAllowed();");
        builder.AppendLine("        return base.SaveChanges();");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public override int SaveChanges(bool acceptAllChangesOnSuccess)");
        builder.AppendLine("    {");
        builder.AppendLine("        EnsureMutationsAllowed();");
        builder.AppendLine("        return base.SaveChanges(acceptAllChangesOnSuccess);");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public override global::System.Threading.Tasks.Task<int> SaveChangesAsync(global::System.Threading.CancellationToken cancellationToken = default)");
        builder.AppendLine("    {");
        builder.AppendLine("        EnsureMutationsAllowed();");
        builder.AppendLine("        return base.SaveChangesAsync(cancellationToken);");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public override global::System.Threading.Tasks.Task<int> SaveChangesAsync(bool acceptAllChangesOnSuccess, global::System.Threading.CancellationToken cancellationToken = default)");
        builder.AppendLine("    {");
        builder.AppendLine("        EnsureMutationsAllowed();");
        builder.AppendLine("        return base.SaveChangesAsync(acceptAllChangesOnSuccess, cancellationToken);");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    private void EnsureMutationsAllowed()");
        builder.AppendLine("    {");
        builder.AppendLine("        if (!_allowMutations)");
        builder.AppendLine("        {");
        builder.AppendLine("            throw new global::DotnetEfCoreMcp.Server.Querying.QueryExecutionException(\"Saving changes from run_query is disabled for this connection.\");");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public object? RunUserAuthoredQuery()");
        builder.AppendLine("    {");

        var queryStartLine = CountLines(builder) + 1;
        if (statementMode)
        {
            AppendIndentedVerbatim(builder, query, 2);
            if (!query.EndsWith('\n'))
            {
                builder.AppendLine();
            }
        }
        else
        {
            builder.Append("        return ").Append(query).AppendLine(";");
        }

        builder.AppendLine("    }");
        builder.AppendLine("}");

        return new GeneratedUserQuerySource(
            builder.ToString(),
            $"{GeneratedNamespace}.{className}",
            queryStartLine - 1,
            statementMode);
    }

    private static void AppendConstructor(
        StringBuilder builder,
        string className,
        string contextTypeName,
        DbContextConstructorShape constructorShape)
    {
        builder.AppendLine("    private readonly bool _allowMutations;");
        builder.AppendLine();

        switch (constructorShape)
        {
            case DbContextConstructorShape.GenericOptions:
                builder.Append("    public ").Append(className)
                    .Append("(global::Microsoft.EntityFrameworkCore.DbContextOptions<")
                    .Append(contextTypeName).AppendLine("> options, bool allowMutations)");
                builder.AppendLine("        : base(options)");
                break;

            case DbContextConstructorShape.NonGenericOptions:
                builder.Append("    public ").Append(className)
                    .AppendLine("(global::Microsoft.EntityFrameworkCore.DbContextOptions options, bool allowMutations)");
                builder.AppendLine("        : base(options)");
                break;

            case DbContextConstructorShape.Parameterless:
                builder.Append("    public ").Append(className).AppendLine("(bool allowMutations)");
                builder.AppendLine("        : base()");
                break;

            default:
                throw new InvalidOperationException($"Unsupported DbContext constructor shape '{constructorShape}'.");
        }

        builder.AppendLine("    {");
        builder.AppendLine("        _allowMutations = allowMutations;");
        builder.AppendLine("    }");
    }

    private static bool IsStatementMode(string query)
    {
        var expression = SyntaxFactory.ParseExpression(query);
        if (!expression.ContainsDiagnostics && expression.FullSpan.End == query.Length)
        {
            return false;
        }

        var statements = SyntaxFactory.ParseStatement($"{{{query}}}") as BlockSyntax;
        return statements is not null && !statements.ContainsDiagnostics;
    }
    private static void AppendIndentedVerbatim(StringBuilder builder, string text, int indentationLevel)
    {
        var indentation = new string(' ', indentationLevel * 4);
        builder.Append(indentation);
        builder.Append(text.Replace("\n", "\n" + indentation, StringComparison.Ordinal));
    }

    private static int CountLines(StringBuilder builder)
    {
        var lines = 0;
        foreach (var character in builder.ToString())
        {
            if (character == '\n')
            {
                lines++;
            }
        }

        return lines;
    }

    private static string GetGlobalTypeName(Type type)
    {
        if (type.IsGenericParameter)
        {
            return type.Name;
        }

        if (type.IsArray)
        {
            return $"{GetGlobalTypeName(type.GetElementType()!)}[]";
        }

        if (type.IsNested)
        {
            return $"{GetGlobalTypeName(type.DeclaringType!)}.{GetTypeName(type)}";
        }

        return $"global::{type.Namespace}.{GetTypeName(type)}";
    }

    private static string GetTypeName(Type type)
    {
        if (!type.IsGenericType)
        {
            return type.Name;
        }

        var tickIndex = type.Name.IndexOf('`');
        var name = tickIndex < 0 ? type.Name : type.Name[..tickIndex];
        var genericArguments = type.GetGenericArguments();
        return $"{name}<{string.Join(", ", genericArguments.Select(GetGlobalTypeName))}>";
    }
}

internal sealed record GeneratedUserQuerySource(
    string Source,
    string TypeName,
    int QueryHeaderLineCount,
    bool IsStatementMode);
